### ISSUE TITLE
Epic 1- Beregn timemålt forbrug for Ellev, Balanceans og net. RSM til aktør. Data kan downloades

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#381]
### Synopsis

As a Datahub Admin user 
I want to be able to see aggregated non-profiled consumption in frontend and download basis data, 
So that I can find results and use them when supporting the market actors

_____________
### Acceptance Criteria

This epic is done when we can do the following in *U001*

- [x] A DH Admin user can assign permissions to existing users in DH3 frontend **(0+1)**.

- [x] Calculate non-profiled consumption per energy supplier, balance responsible and per grid area **(2)**, based on PRE07 data **(4)**. 

- [x] A DH Admin user can invite new users and in DH3 frontend **(3)**.

- [ ] Basis data is generated for non-profiled consumption and Datahub Settlement Admin user are able to login to Datahub 3 and download basis data for the grid access provider **(5)**.

- [x] DH Settlement Admin users are able to login to Datahub 3 and view aggregated non-profiled per grid area, balance responsible and energy supplier **(5)**.

- [x] Energy suppliers, balance responsible and meter data responsibles are able to peek/dequeue RSM-014 in CIM XML with aggregated non-profiled consumption contained in the message **(6)**. 

TEST FLOW
This epic is done when we can do the following in *U001*

- [ ] 0) Mads kan ikke start batch
- [ ] 1) Torben tager skærmen og giver rettigheder til Mads
- [ ] 2) Mads start batch
- [ ] 3) Der oprettes ny bruger (TML).
- [ ] 4) Data er pre07 (PTH).
- [ ] 5) Energinet brugeren kan se El-leverandører, balanceansvarlige's resultater I frontend (MND). (minus netområde) (Måske vis i powerBI)
- [ ] 6) Der kan peek/dequeues (CMY)
- [ ] 7) Afregnings rapporter (MND)
