### ISSUE TITLE
Epic 2 - Midlertidig flex forbrug uden nettab+ Netto udveksling per net og per nabonet bliver beregnet. Beregnings resultat bliver nu udvidet med CIM JSON

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#403]
## Use Cases

_(Som en DH 3 admin kan invitere en ny bruger til DH3 så den nye bruger kan logge ind på DH3.)_ **Skal prioriteres af Mogens.** @mogensjuul 

Som netvirksomhed vil jeg modtage netto udveksling pr. netområde I en RSM-014 så jeg kender resultatet for udvekslingen.

Som datahub 
Vil vi beregne udveksling per nabonet til eSett 
så vi kan enable fremsende til eSett i epic 3

Som DH Admin bruger
Vil jeg kunne fremsøge alle de RSM-014 beskeder som vi sender ud til markeds aktørerne
Så vi kan overholde revisionskrav og bruge det til bedre at kunne fejlsøge i support sager. 
Som Datahub
vil vi gøre det muligt for el-leverandørerne, balance ansvarlige og måledataoperatørerne at hente RSM-014 beskeder i CIM JSON, så vi kan understøtte de aktører, der vælger at bruge det format. 
Som Datahub
ønsker vi en produktionsmoden migringsplatform, så tidsserier og stamdata kan flyttes hurtigt, sikkert, cost-effektivt og stabilt fra Datahub 2 til Datahub 3. 
Som en DH3 bruger vil jeg kunne logge på DH og navigere rundt i UI 
Som en Energinet systemadmin vil jeg kunne lukke en brugerrolle
Som DH bruger vil jeg kunne fremsøge rettigheder og kunne se en beskrivelse af dem
Som Energinet-, elleverandør- og netvirksomheds-bruger kan jeg benytte 'Afregningsskærmbilledet (Mandalorian/Titans samarbejde)

_____________

## Acceptance criteria
**Titans**
- [x] DH brugere kan logge ind på DH UI
- [x] En Energinet systemadmin kan lukke en brugerrolle
- [x] En DH bruger vil kunne fremsøge rettigheder og kunne se beskrivelser af disse
- [x] Det er muligt at styre hvilke informationer (egne) en aktør kan se på UI
- [x] Energinet-, Elleverandør- og netvirksomheds-brugere kan benytte afregningsskærmbilledet (Mandaloran/Titans samarbejde)

**Volt**
 - [x] Migreringsplatformen skal effektiviseres, så den er optimeret i de 5 søjler som Microsoft beskriver om best practice; i følgende prioritet: Pålidelig, sikker, driftbar, højtydende, prisoptimeret. Ikke længere kun til indlæsning af bulk-data, men også forberedt til kontinuerlig levering af stamdata og tidserier fra Datahub 2. 
- [x] Feedback fra Eloverblik vedr API'et. 

**Mandalorian**
- [x] Beregn netto udveksling per net 
- [x] Beregn netto udveksling per nabonet
- [x] Beregn Flex forbrug per aktør 

**Batman**
- [x] Aktører skal kunne modtage beskeder i JSON formatet
- [x] FAS brugere skal kunne fremsøge alle udsendte RSM-014 beskeder i det eksisterende skærmbillede. 
- [x] Wholesale forbereder løsning til hvordan EDI domænet kan håndtere anmmodninger. Arkitekter afklaring.

<br>

- [x] Opgaven omkring genimplementering af Landing zone skal refines. En genimplementering skal sikre, at dataleverander fra Datahub2 leveres gnidningsfrit til Datahub 3, på en måde som understøtter kontinuerlige målepunkts- og tidsserieleverancer. 

<br>

Ikke udførte ac overføres til Epic 3
- [x] udsendelse af netto udveksling per net (Mandalorian har haft udfordringer med at få data hurtigt nok op at delta laken)

Ekstra funktionalitet
- [x] en bruger kan anvende MitID som adgangsmetode til DataHub
