### ISSUE TITLE
Calculate Net exchange per neighboring grid area

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#415]
### Synopsis
As datahub
we want to calculate net exchange per neighboring grid area
so we can support esett in doing an imbalance settlement 

### AC
- [x] When triggering a new batch, Then net exchange per neighboring grid area and per grid area is calculated
- [x] The calculation is performed using the following example: https://energinet.sharepoint.com/:x:/r/sites/Joules/_layouts/15/Doc.aspx?sourcedoc=%7BFC1636B2-C77A-4263-B2BB-0294090F6938%7D&file=ExchangePerNeighboringGrid.xlsx&_DSL=1&action=default&mobileredirect=true
- [x] Developers help SME/PO finding results for a specific test case by prepareing a SQL query in databricks, to find results in delta table for grid area 804 i T environment. 

### Tasks
- [x] Fix problem with exchange breaking writing to delta (introduce results_table_schema) @BjarkeMeier 
- [x] Establish a way for PO and SME to verify results @MadsBloendAndersen  
Add PO and SME to an AD group with suitable permissions?
- [x] Deploy relevant queries/dashboards in pipelines @BjarkeMeier
- [x] Calculate exchange per neighboring grid area @BjarkeMeier 
- [x] Add integration tests (calculator_job tests) of calculations that are written to delta results table @BjarkeMeier
- [x] Test that only expected enum values are written to delta results table @BjarkeMeier 
Talk to Halfspace about the best solution
- [ ] ~~Should we remove all the complicated lock and stop processes stuff in CD related to migrations as they were needed for the file based approach and not the new delta based design?~~
- [ ] ~~Should we (a) remove all the file based results and corresponding code (and thus break the front-end) or (b) transition to reading from the delta table or (c) do nothing?~~
- [x] Change from OUT-IN to IN-OUT (see comment by Mads below) @BjarkeMeier 
- [x] Rename all "in grid" and "out grid" to "to grid" and "from grid"
- [x] Fix [introduced bug](https://adb-8850306791656298.18.azuredatabricks.net/?o=8850306791656298#job/504951666303575/run/348466) @BjarkeMeier 
Why can't we enable debug|verbose anymore in calculator_job?
```
IllegalArgumentException: [CAST_INVALID_INPUT] The value 'net_exchange_per_neighboring_ga' of the type "STRING" cannot be cast to "DECIMAL(18,3)" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
```
- [x] Jesper requested migration history files on u-001 and t-001 (and other envs?) to be truncated
- [x] Find and fix DH2/DH3 result differences (see comment by Mads below) @BjarkeMeier solved according to SME?
- [x] Fix that dashboard is not being published by CD @BjarkeMeier (PR merged)
- [ ] ~~Prevent missing delta table in hive when databricks workspace is recreated~~
~~And Use delta table names instead of path/location for input tables?~~
- [x] Stop using managed tables in order to prevent accidentally deleting production data @BjarkeMeier 
Read more at https://learn.microsoft.com/en-us/azure/databricks/lakehouse/data-objects#--what-is-a-database
- [x] Fix deployment to t-001 (migrations are failing)

### Tech Notes
As a temporary hack PO and SME can be granted the relevant permissions to execute SQL queries by an administrator by executing the following statements (on relevant environments):
```sql
GRANT SELECT ON TABLE wholesale_output.result TO `mnd@energinet.dk`;
GRANT USAGE ON SCHEMA wholesale_output TO `mnd@energinet.dk`;
GRANT SELECT ON TABLE wholesale_output.result TO `kwq@energinet.dk`;
GRANT USAGE ON SCHEMA wholesale_output TO `kwq@energinet.dk`;
```

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen and @khatozen, how is the resulting quality calculated?

**Comment by khatozen** [comment]
@BjarkeMeier and @MadsBloendAndersen Quality "Calculated" is used in RSM-014 only when all included time series have quality calculated. The aggregated time series for exchange will never get quality calculated.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier + @khatozen I've been looking into the basis data for the calculation on net exchange. 

When I look at the wholesale gold table, I find the following exchange metering points that are valid for the first 15 min of the calculation period (January 2022)

1. 571313180400109995
2. 571313180400109889

Everything is summed up here: 
![image](https://user-images.githubusercontent.com/72008712/232769266-d3f557bb-3fbd-4fe9-a539-45f9ee5ec876.png)

And it suggests that the results for net exchange in DH3 are calculated like this: Net_exchange = OUT-IN 

Instead of: Net_exchange = IN-OUT

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier There is another issue. But i think it is a data issue, maybe coming from volt.

When I compare net exchange from DH2 with DH3, they I get a significant difference in results. 
see screendump. 
![image](https://user-images.githubusercontent.com/72008712/232772021-b1b849b4-648e-40dc-a3ec-48da98a43601.png)

**Comment by khatozen** [comment]
Agree with Mads, Net_exchange = IN-OUT.
To get the correct result for the exchange we have to execute the balance fixing for all grid areas that have exchange with 804.
