### ISSUE TITLE
Epic 3 - Beregn nettab og system korrektion + klargør beskeder til eSett + anmodninger + modning af eloverblik API

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#420]
### Use cases

**Nettab** mandalorian
Som DH3 vil vi beregne nettab og system korrektion, så vi kan justere summer for flex forbrug og produktion for relevante aktører.

**Esett** Titans
Som datahub vil vi forberede udsendelse af aggregerede tidsserier til eSett så vi kan koble besked flowet op på ECP/BizTalk 
Analysedelen af eSett kommunikationen ligger her. Hvilke dele skal beholdes/erstattes.

**Udsendelse**  batman
Som aktør vil jeg kunne peeke og dequeue beskeder, så jeg kan modtage mine data for energi afregning

**Anmodninger** batman
Som aktør vil jeg kunne indsende en admoning om aggregeret energitidsserier gennem B2B, og få svar i HTTP kaldet. 

**Migrering** Volt
Som migrerings platform vil vi refine vores landing zone, så den er forberedt til både bulk og synkroniseringer. 

**Afregningsrapporter** Titans
Som datahub afregnings admin vil jeg kunne hente afregningsrapporter med resultatdata, så jeg kan kontrollere at datahub regner det samme som DH2

### Acceptance criteria

- [x] Givet et batch er startet, når nettab og system korrektion bliver beregnet, Så bliver summerne på de aktører som er ansvarlige for nettab og system korrektion justeret. 
  
- [x] Givet et batch er startet, når batchet er afsluttet, så bliver resultater samlet til eSett og forberedt til bizTalk/ECP 

- [x] Givet et batch er afsluttet, når en aktør, som er en del af beregningen, peeker og dequeuer deres beskeder, så vil de modtage de relevante data.

- [x] Givet en aktør, når man indsender en anmodning om aggregerede energi tidsserier, så bliver beskeden synkront valideret og aktøren får svar tilbage. 
- [x] Reimplementer vores landing zone, så det understøtter vores synkroniseringer. Altså at der kan peekes og dequeues tidsseriebeskeder fra DH2. 
- [x] Det er afgjort hvilke dele af eSett kommunikationen der skal beholdes og hvilke dele, der skal erstattes
- [x] Som datahub afregnings admin vil jeg kunne hente afregningsrapporter med resultatdata
