### ISSUE TITLE
Epic 4 - Opstart af engros afregning + Fremsøg beregnings resultater og kurvekontroller + Import af Bulk migrerede prod-data tidsserier til Eloverblik 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#421]
### Use cases
**Esett**  Titans
UC1: Som esett vil jeg kunne modtage beskeder fra **PRE07** så jeg kan eksekvere balanceafregning 

UC2: Som datahub data og valideringsteam skal jeg kunne monitorere aktuel status herunder gensender beskeder hvis der er behov herfor

UC4: Som esett vil jeg kunne modtage beskeder fra **DH3 test** til esett, så jeg er klar til balanceafregning, når fase 1 igangsættes

UC5: Som DataHub bruger vil jeg opleve forbedringer på brugerprofilen så jeg kan skifte telefonnummer og password

**EDI** Phoenix

UC; Som en aktør vil jeg kunne modtage svar på min anmodning om beregnede energi tidsserier. 

UC 5: Som aktør skal jeg kunne anmode om aggregerede tidsserier via FrontEnd (BRS-026) fordi nogle aktører ikke har mulighed for at anmode via B2B.

UC 6: Som aktør vil jeg kunne modtage beskeder i eBix-formatet, så jeg kan anvende eksisterende løsning i fase 1 og 2

**Kontroller**  Mandalorian data ansvarlig mangler  -- Definer HVordan vi får en ressource til BI løsning
UC 7: Som data og validerings team vil vi have adgang til et system hvor vi kan se resultater fra beregningen så vi kan fejlsøge 

UC 8: Som data og validerings team vil vi have en rapport som indikerer mulige fejlkilder, så vi nemt  kan lave opfølgning

UC 9: Som data og validerings team vil vi have adgang til et system hvor vi kan se kurver over nettab og netområdeforbrug ++ , så vi kan kontrollere at data er som det skal være BI-Opgave

UC 10: Som datahub vil vi finde ud af hvordan vi skal verificere at datahub 3.0 regner rigtig, så vi kan rapportere til markedet at vi er klar til produktion (Skyggeafregning i prod )  

**Beregninger** (Mandalorian)
UC 11: Som afregningsadmin vil jeg kunne starte en engrosfiksering, som kan beregne produktion og forbrug pr time tarif per aktør, så vi anvende data til engrosafregning

UC 12: Som afregningsadmin vil jeg kunne starte en engros afregning som månedsummer, som kan beregne produktion pr tarif per aktør, så vi anvende data til engrosafregning

Migrering: (Volt)
UC 13: Vi vil modtage bulkeksporterede tidsserier, helst i form af prod-data på et prod-miljø, så de kan leveres til eloverblik. 

### Afhængigheder
1. UC 7: Løsning for udstilling af data --> Søren er i dialog med CA og data platform omkring en løsning.
2. UC 6: Christian driver afhængigheden mellem The Outlaws og Batman i forhold til at kunne understøtte SOAP i API Management.

### Acceptance criteria
- [x] Kontrakten på priser er aftalt med migrerings team og wholesale har implementeret statisk datasæt
- [ ] Nye proces typer er implementeret (Wholesale fixing + correction settlement med alle proces varianter)
- [ ] Givet et batch er startet, når beregningen af afsluttet, Så vil vi kunne fremsøge resultater for flex forbrug per tariff
- [ ] Når man kører en engros beregning, bliver der både beregnet resultater til RSM-014 og RSM-019
- [ ] Vi skal kunne beregne månedssummer for flex forbrug per tariff
- [ ] Tilføj mulighed for at køre engros beregninger på månedsbasis
- [x] Levering af bulk-migrerede tidsserier til eloverblik, baseret på proddata. Her imødeses et stort kvalitetssikringsarbejde for tidsserierne. 

- [ ] Givet data og validerings teamet, når de vil undersøge resultater for en balance fiksering og aggregering, så vil de kunne slå resultater op i et system, og filtrere på netområde, aktør, periode, målepunktstype, afregnignsform.
- [ ] Givet data og validerings temaet, når de vil kontrollere om data ser korrekte ud, så vil de have adgang til et system som kan tegne nettabs kurver for en bestemt periode.
 
- [x] En bruger kan, når de anmoder om beregnede energi tidsserier via frontenden  peeke svaret i enten CIM XML eller CIM JSON
- [x] En aktør kan, når et beregningsresultat foreligger, peeke beskeden i eBix formatet. 

- [ ] Givet vi har alle beregninger på plads og klar til at gå i prod, når vi vil kontrollere om vi beregner rigtigt, så skal vi have en metode på plads for hvordan det skal gøres.

- [ ] DH3 skal kunne modtage meddelelser fra DH2, konvertere dem til NBS format og sende dem til eSett
- [ ] DH drift skal kunne overvåge om meddelelserne når frem til eSett / afvises
- [ ] DH3 drift skal kunne genfremsende meddelelser til eSett
- [ ] DH3 skal kunne modtage meddelelser vedr. balanceansvarlige aktørrelationer fra eSett  
- [ ] Givet en bruger er logget ind kan han ændre telefonnummer og password

### Noter
