### ISSUE TITLE
Epic 5(gammel) - Beregning af flex og time forbrug og child målepunkt per tariff. Vi kan delegere og fremsende engrosbeskeder og sende nettab/systemkor til DH2. Vi understøtter opstarten af aktørtesten.

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#422]
### Use cases

UC: Som datahub skal jeg kunne opstarte IT-lev/aktør test, så aktører kan blive onboardet og klar til at modtage de energitidsserier

**Titans**
UC1: Som datahub vil vi sende system korrektion og nettab til DH2 (via soap kald og RSM-012?)

**Mosaic**
UC 2: Som DH ønsker jeg at opsætte metrikker for B2B kanalen, således at vi kan bygge noget monitorering. 

UC 3: Som datahub skal jeg kunne fremsende meddelelser omkring engrosafregning til aktører

UC 4: Som aktør skal jeg kunne delegere mine  ind- og udgående meddelelser til andre aktører. 

**Volt / Migrering**
UC 5: Som migreringsteam skal jeg kunne peeke og dequeue synkroniserede tidsserier via aftalt format med Cgi, på dagligt basis,  så jeg kan stille dem til rådighed for el-overblik - hermed kan eloverblik gå live med migrerede data. 

UC 6: Som migreringsteam vil vi migrere produktionsdata som bulk tidsserier og bulk målepunkter, kvalitetssikre dem og udstille dem, så de kan indgå i en energiafregning. 

UC 7: Som risikomitigerende foranstaltning vil vi udvikle og teste, men ikke endeligt implementere konverteringen af prislinks og priser til Datahub 3,0 format. Selve konverteringen forventes at være kompleks, så det er for at danne et tidligt erfaringsgrundlag for næstkommende epic. Det afvikles som en time boxed aktivitet. 

**Mandalorian**
UC 8: Som datahub vil vi beregne flex og time forbrug per tariff så vi kan levere data til engros opgørelsen

UC 9: Som datahub vil vi beregne energimængder per child målepunkt per tariff, så vi kan levere data til engros opgørelsen

UC 10: Som datahub vil vi ekskludere udveksling per nabonet og summer per balance ansvarlig i engros afregningen, så vi kan køre for enkelte net ad gangen og fordi disse beregninger ikke er relevante for engros afregning.

UC 11: Som afregnings admin vil jeg have fejltekster når et batch fejler, så jeg ved hvad fejlen er, og jeg evt. kan rette op på det. 

**The Outlaws**
UC 12: Som migrerings platform vil vi kunne restore migreringsdata fra en backup, så vi sikrer at data kan genindlæses under en technical recovery

UC 13: Som aktør vil jeg kunne bruge datahub's APIM endpoint til at foretage en connection test, så jeg kan validere om der er forbindelse mellem mit IT system og DataHub 3.0 

### Afhængigheder
1. UC1: CGI. Som beskrevet skal løsningen indeholde en RSM-012 tilbage til DH2. Denne funktionalitet kræver en RFC til DH2 (CGI)
2. UC1: IP whitelisting i firewallen hos Energinet (Titans, The Outlaws, CA)
3. UC6: Energiafregning vs bulk tidsserier og målepunkter (Mads afklarer)

**Acceptkriterier**

- [ ] Det skal være muligt at monitorere om beskeder bliver peeket på B2B kanalen. [Mosaic]
- [ ] Vi ønsker at måle på hvor længe det tager at peeke beskeder [Mosaic]
- [ ] Vi ønsker at være i stand til at omdanne resultater fra engroafregning til beskeder, så aktøren kan peeke og dequeue de pågældende beskeder [Mosaic]
- [ ] Det skal være muligt for en aktør at indsende og modtage beskeder på vegne af en anden aktør (delegering) [Mosaic]
- [ ] Alene som Proof of concept; vi ønsker at kunne gennemføre konvertering af en pris og et prislink fra dh2 logik til dh3 logik. Priser bliver ikke udstillet i guldlag, der er alene tale om selve algoritmen [Volt]
- [ ] Vi skifter over til at levere tidserier til eloverblik via den synkroniserede løsning, således at de har et datagrundlag for at gå live via migrerede data. [Volt]
- [ ] Vi leverer bulkmigrerede målepunkter og tidsserier til wholesale (her imødeses et kvalitetssikringsarbejde i prod-målepunkter)[Volt]
- [ ] Vi skal kunne beregne mængder for flex og time forbrug per time og dags tariffer og publicere resultater
- [ ] Vi skal kunne beregne mængder for child målepunkter per time og dags tariffer  og publicere resultater
- [ ] Når vi beregner engros afregning skal vi eksludere udveksling per nabonet og summer per balance ansvarlige
- [ ] Når et batch fejler skal man kunne finde fejlen meddelelsen i frontenden
- [ ] Når systemkorrektion og nettag er beregnet i DH3 skal disse data sendes til DH2, der derefter  sender beskederne videre til elleverandør og måledataansvarlig [Titans]
