### ISSUE TITLE
[Mosaic] Aktør kan modtage beskeder i eBix format

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/green-energy-hub#445]
Som en aktør
Har jeg behov for at kunne modtage RSM-012 beskeder i eBix format
Da det er et krav i fase 1 og noget vi forventer

Netvirksomheder, balanceansvarlige og elleverandører forventer at de kan kan modtage beskeder i eBix formatet. Det betyder at vi skal understøtte dette format. Dette format skal kun understøttes i fase 1. 

OBS: eBix benytter SOAP protocoller og modsat vores nuværende løsning (DH3) som benytter tokens så bruges der certifikater ved eBix SOAP. Outlaws er i gang med at tilpasse APIM til at understøtte eBix. 

**AC'er**
- [ ] En netvirksomhed kan peeke beskeder i eBix formatet
- [ ] En balancesvarlig kan peeke beskeder i eBix formatet
- [ ] En elleverandør kan peeke beskeder i eBix formatet
