### ISSUE TITLE
[Mandalorian] Data delivery to EDI domain per grid area

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#447]
## Synopsis
As wholesale, we want to deliver exchange per grid area and non-profiled consumption results to EDI, enabling them to forward messages to the grid access provider. 

## Accept criteria
**Grid access provider**
- [x] Given a batch with execution type "actual" When completed Then **net exchange** per grid area, is published
- [x] Given a batch with execution type "actual" When completed Then **non-profiled** per grid area, is published
**Energy Supplier**
- [x] Given a batch with execution type "actual" When completed Then **non-profiled** per energy supplier, is published 
- [x] **Balance responsible**
- [x] Given a batch with execution type "actual" When completed Then **non-profiled** per balance responsible, is published 
- [x] Given a batch with execution type "actual" When completed Then **non-profiled** per energy supplier per balance responsible, is published
- [x] Given a Batch with execution type "Actual" When completed Then **ALL OTHER timeseries types per actor**, is published. (Flex and production **WITHOUT** system correction and grid loss)
Note: Accept criteria will be completed in #1264

**Misc.**
- [x] Given the results, when published, Then we check that the period and process type matches the period and process type of the batch. 
- [x] EDI has accepted the delivery
- [x] All code related to file based results have been removed

## Tasks

- [ ] Share delta migration code with .NET tests to avoid duplication @BjarkeMeier 
- Use plain Databricks SQL in SQL files @BjarkeMeier 
- Reuse the SQL in .NET tests testing results
- Consider splitting pyspark migrations into own wheel

### Done Tasks

- [x] Publish the events
- [x] Publish with correct meta data including process type (not everything as balance fixing)
- [x] Make support for chunks of data in SqlStatementClient (multiple response messages from warehouse) @BjarkeMeier 
- [x] Move settlement report code to delta based results @BjarkeMeier 
- [x] Remove all code related to creating and reading file based results @BjarkeMeier 
- [x] Add "from grid area" to calculation results - including the public contract. And use it to distinguish results @BjarkeMeier 
- [x] Fix domain tests @johevemi 
- [x] Use calculation result id @JesperGomes 
- Add result id column to delta table (UUID/sequence number/...?)
- Update existing data
- Use to distinguish results in class CalculationResultQueries
- Order by CalculationResultId and then by time  in class CalculationResultQueries
- [x] Fix read of chunks @BjarkeMeier 
- [x] Add integration tests that read chunks. The test will be based on data generated by SQL in the test @BjarkeMeier 
- [x] Fix skipped test Parse_WhenResultIsChunk_ReturnsExpectedNextChunkInternalLink @BjarkeMeier 
- [x] Use serverless SQL warehouse to avoid 5 min latency on first request @BjarkeMeier /Outlaws
STATUS (6/7): A story is on the Outlaws backlog and team Mandalorian has thus decided to close this task
STATUS (14/6): Outlaws PO expects to enable serverless in the sprint week 26/27
[PR ready](https://github.com/Energinet-DataHub/dh3-infrastructure/pull/282) but can't/must not be merged
See more [here](https://teams.microsoft.com/l/message/19:Z45YOniw4YUFEnENKgbKOHgtjbf1axySzUZ_jivnYiU1@thread.tacv2/1684314328617?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=38e0432b-6379-40d1-9b3a-b1b90c48de70&parentMessageId=1684314328617&teamName=The%20Outlaws%20-%20Public&channelName=General&createdTime=1684314328617&allowXTenantAccess=false)
UPDATE 24/5: Requires some firewall setup by Outlaws. See [this issue](https://github.com/Energinet-DataHub/team-the-outlaws/issues/1144).
At first we looked into always-on for warehouses, but it turned out to seem pretty expensive

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen as the ACs explicitly mentions that results should be published for "actual" batch executions - does that imply that simulated executions should _not_ cause publishing? Otherwise we should probably remove "actual" in the ACs to avoid confusion.
