### ISSUE TITLE
Epic 6  gammel - Engros beregninger færdiggøres og udsendes. Simulering er muligt. Anmodninger af engrosydelser. Eksterne aktører kan interagere med testmiljø. 

### ISSUE THREAD

**Issue by mogensjuul** [Energinet-DataHub/green-energy-hub#450]
### Use cases

**Ikke fordelt endnu - er stadig i refinement**
UC0: Som datahub skal jeg klargøre testmiljøet så aktører kan få adgang fra Epic 7. (Klargørings acceptkriterier foregår i næste sprint)

UC0: Hvor er behovet for en Scheduler: afklares.

**Titans**
UC1: Som datahub skal vi Definere fælles løsning for audit tracking som de øvrige teams kan anvende til domænets audti tracking **(tema ikke ok)**
UC2 :  Som datahub skal vi Hente Ubalancepriser fra esett via ecp så wholse sale kan anvende dem i fakturering efter engrosafregning  ( Obs. Det skal være konverteret til danske kroner. (Kontrol Center)

**Phoenix**
UC1: Vi skal understøtte resterende beregninger fra engros afregning 
UC2: Vi skal understøtte aktørens behov for at anmode om engrosafregning via B2B
UC3: Vi skal understøtte aktørens behov for at anmode om engrosafregning via frontend 

**Volt / Migrering**
UC1 : Som migreringsteam ønsker vi at migrere ebix baserede priser og prislinks til pristidsserier, prisinformationer og prislinks, således at mandalorian kan anvende disse i engrosafregninger. **(tema ikke ok)**

**Mandalorian**
UC1 : Som datahub vil vi beregne mændger per gebyr og abonnementer per aktør, så vi kan udesende en færdig engros opgørelse.
UC2: Som data og validerings team vil vi have mulighed for at at køre beregninger som ikke bliver sendt ud til markedet, så vi kan kontrollere beregningerne uden det påvirker markedet **(tema ikke oK)**
UC3: Som markedsaktør vil jeg kunne peeke/dequeue data med jævne mellemrum, så vi kan kontrollere afregningsdata.**(tema ikke oK)**

**The Outlaws**
UC: **(slet denne eller udfyld)**

### Acceptkriterier 
**Volt / Migrering**
- [ ] Givet at vi har adgang til migrerede-bulkdata, når vi indlæser charges information og charge prices fra datahub 2, så migreres disse, udstilles disse i to guldtabeller til mandalorian, således at formatet og leverede data kan verificeres. [Volt]

- [ ] Givet at vi har adgang til migrerede-bulkdata, når vi indlæser alle charge links fra datahub 2, så migreres disse, udstilles disse i en guldtabel til Mandalorian; [Volt]
- [ ] Givet at vi har indlæst alle historiske og aktuelle prod-charges fra Datahub 2, når alle bulkdata er leveret til guld, så omkonfigureres løsningen til fortløbende at migrere charges og levere disse, så Mandalorian kontinuerligt får aktuelle charges. [Volt]
**Phoenix**
- [ ] Som en aktør har jeg behov for at kunne modtage de resterende beregninger fra engrosafregningen. [Phonenix]
- [ ] Som en aktør har jeg behov for at kunne anmode om engrosafregninger via B2B [Phonenix]
- [ ] Som en aktør har jeg behov for at kunne anmode om engrosafregninger via frontenden  [Phonenix]
**Titans**
- [ ] Som DataHub har jeg et behov for en defineret løsning til anvendelse af auditlog - central eller decentral - for at kunne understøtte revisionskrav [Titans]
- [ ] Som DataHub har jeg et behov for at kunne hente ubalancepriser fra eSett for at kunne lave en korrekt fakturering [Titans]
**Mandalorian**
- [ ] Givet en en engros beregning, når afsluttet så bliver mængder per gebyr og abonoment beregnet og publiseret til EDI, til videre udsendelse.
- [ ] Givet en beregning (engros eller energi), når afregnings admin vil starte batch, så har de mulighed for at vælge eksekveringstype "Simulering"
- [ ] Givet en beregning, når eksekveringstype er "Simulering" så bliver der ikke publiseret events til EDI
- [ ] Givet en simulering, når kontrolleret at data er på plads, så skal den kunne ændres til en faktisk kørsel og der vil nu blive sendt resultater ud til markedet for den pågældende beregning. 
- [ ] Givet en aktør, når de tester i testfasen så skal de modtage beregningsresultater med jævne mellemrum (hver time)

**Comment by Christian-Meyer** [comment]
Indsat fra story:
Forventet periode: 4 sprints

Testmiljøet stiller beregninger til rådighed som aktører kan peeke/dequeue RSM014/RSM019 og anmode via RMS016
Aktører skal kunne hente afregningsdata summeret og grunddata
Aktører og support kan se indsendte og udsendte beskeder
Vi skal være i stand til at kommunikere effektivt med aktører.

Krav til miljø.
- Hyppighed omkring udsendelse af afregningskørsler
