### ISSUE TITLE
Closer to production grade delta table migrations

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/green-energy-hub#468]
## Synopsis
Everybody wants production-grade implementation.
Can we improve the overall project progress by sharing the solution with Volt?

## Accept criteria
- [x] Make delta migrations simpler and more tailor-made by using plain Databricks SQL @BjarkeMeier 
- [x] Share delta migration code with .NET tests to avoid duplication

## Tasks

- [x] Use plain Databricks SQL in SQL files @BjarkeMeier 
Pretty much done. Open PR [here](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1287).
But somehow it doesn't work in CD. Debug in progress with the dh3environments branch `bjarke/debug-delta-migrations`.
- [x] Talk to Halfspace about the concept (in order to get feedback on concept and pros/cons/alternatives)
- [x] Reuse the SQL in .NET tests testing results
- [x] Refac python code so it replace the TEST keyword and update SQL script with TEST.
- [x] Review with Jesper/Bjarke
