### ISSUE TITLE
Calculate production in kWh per hourly tariff per energy supplier. 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#470]
# Synopsis
As datahub
We want to calculate the energy in kWh for the total production per hourly tariff per charge owner, per energy supplier per grid area
so we can calculate the amount for the production for hourly tariff.

# Acceptance criteria
- [ ] Given a wholesale calculation, when started, then DataHub must aggregate the energy in kWh for production metering points per hourly tariff per charge owner per balance supplier per grid area for each hourly tariff linked to a production metering point.
- [ ] Given a wholesale calculation, when started, then the aggregated result is in hourly resolution.
- [ ] Given quarterly measured metering points, When included in a wholesale calculation, then they are aggregated on an hourly resolution.

# Tasks
- [x] Rewrite test_charges_reader.py @energinet-ajw 
- [x] Rewrite test_factories.py @johevemi 
- [x] Refactor calculation-input "interface" @BjarkeMeier 
- [x] Remove test schemas that are no longer used in 'test_factories.py'~Move test schemas to production code and assert schema of input data frames where applicable~ @JesperGomes 
- [x] Check schemas in calculation_input/calculation_input_reader.py @energinet-ajw 
- [x] Add links to schemas to Confluence (maybe easier to find information) @energinet-ajw 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGhwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea6dccbe7be6d747e69fa09d4750722da776f629/image.png)
https://docs.databricks.com/en/delta/update-schema.html#explicitly-update-schema-to-change-column-comment-or-ordering

**Done**
- [x] Why are there no data in wholesale table? @JesperGomes 
- [x] unit test calculate_tariff_price_per_ga_co_es @JesperGomes
- [ ] ~Should we change charge_id to charge_code~ Volt will get to this topic when they look into the contract (soon)
- [ ] ~Modify get_tariff_charges(..) to use enriched_time_series as input (and not metering_point, time_series and market_roles)~ maybe not worth the effort to do this?
- [x] Get charge test files for integration tests (that works with MeteringPointPeriods.csv) @MadsBloendAndersen 
- [x] Use new charge tests files as part of integration tests @JesperGomes 
- [x] Python enums should be upper case
- [x] Add tests of get_tariff_charges(...)
- [x] Rename existing table: 'result' -> 'energy'? (consider renaming schema as well: wholesale_output -> calculation_output?) @BjarkeMeier 
- [x] Fix flaky test
- [x] New migration script for creating wholesale result table @BjarkeMeier 
- [x] Use correct charge type names @BjarkeMeier 
```sql
update charge_link_periods set charge_type = 'subscription' where charge_type = 'D01';
update charge_link_periods set charge_type = 'fee' where charge_type = 'D02';
update charge_link_periods set charge_type = 'tariff' where charge_type = 'D03';

update charge_masterdata_periods set charge_type = 'subscription' where charge_type = 'D01';
update charge_masterdata_periods set charge_type = 'fee' where charge_type = 'D02';
update charge_masterdata_periods set charge_type = 'tariff' where charge_type = 'D03';

update charge_price_points set charge_type = 'subscription' where charge_type = 'D01';
update charge_price_points set charge_type = 'fee' where charge_type = 'D02';
update charge_price_points set charge_type = 'tariff' where charge_type = 'D03';
```
- [x] Write whosale results to delta lake @BjarkeMeier 
- [x] Introduce enums needed for working with wholesale_results table @BjarkeMeier 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdndzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8fea383611e241809bf7375413557b61ae2f4a64/image.png)
- [x] Use child metering point type names @BjarkeMeier 
- [x] Migrate from time_series_type to metering_point_type/settlement_method instead in our codebase and in contracts (we are keeping time_serie_type for energy calculations, a comment has been added to it)
- [x] Add lost energy table constraints on t-001 @BjarkeMeier
- [ ] Map settlement method codes to names during reading from migrations data so that all calculations and results are using names (this updates some data in the energy_result table) @BjarkeMeier 
- [x] Map metering point type codes to names during reading from migrations data so that all calculations and results are using names (this updates some data in the energy_result table) @BjarkeMeier 
- [x] Improve tariff calculations including writing new tests @BjarkeMeier 
Also test that group by works as intended for production (where settlement methods is null)
- [x] Add tests of scale, precision, rounding @BjarkeMeier 
- [x] Change "batch_" -> "calculation_" in delta table columnsAlign naming of the energy_results table with the new wholesale_results table (column names)  @BjarkeMeier 
- [x] Add missing energy table constraints (see wholesale_results table)  @johevemi / @BjarkeMeier 
- [x] Validate mapping of metering point types and settlement methods in calculation input @BjarkeMeier 
- [x] Calculate correcct quality instead of using hard coded values @BjarkeMeier

**Comment by MadsBloendAndersen** [comment]
@JesperGomes I think this should fit with the existing metering points in the integration test.

[ChargeLinks(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12356623/ChargeLinks.Auto.csv)
[ChargePrices(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12356624/ChargePrices.Auto.csv)
[Charges(Master).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12356626/Charges.Master.csv)

**Comment by MadsBloendAndersen** [comment]
@JesperGomes New data here, that fits with format: 

[ChargeLinks(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12376290/ChargeLinks.Auto.csv)
[ChargePrices(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12376291/ChargePrices.Auto.csv)
[Charges(Master).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12376292/Charges.Master.csv)

**Comment by MadsBloendAndersen** [comment]
@JesperGomes Try with this new data: 
[Charges(Master).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12377517/Charges.Master.csv)


[ChargeLinks(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12377515/ChargeLinks.Auto.csv)
[ChargePrices(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12377516/ChargePrices.Auto.csv)

**Comment by MadsBloendAndersen** [comment]
@JesperGomes try this new data

[ChargeLinks(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12394026/ChargeLinks.Auto.csv)
[ChargePrices(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12394027/ChargePrices.Auto.csv)
[Charges(Master).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12394028/Charges.Master.csv)

**Comment by MadsBloendAndersen** [comment]
new test data that fits with PRE07 data 

[ChargeLinks(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12513534/ChargeLinks.Auto.csv)
[ChargePrices(Auto).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12513535/ChargePrices.Auto.csv)
[Charges(Master).csv](https://github.com/Energinet-DataHub/green-energy-hub/files/12513536/Charges.Master.csv)
