### ISSUE TITLE
Publish the calculated production per hourly priced tariff per energy supplier to EDI

### ISSUE THREAD

**Issue by khatozen** [Energinet-DataHub/green-energy-hub#476]
As DataHub
We want to send the calculated energy, tariff price and calculated amounts for production per hourly tariff  to the EDI
so that the actors can get the calculated wholesale settlement.

# Acceptance criteria
- [ ] Given a wholesale calculation, when started, Then DataHub must send the following to EDI:

> - Calculated energy in #470 

> - Get the prices for the hourly tariffs 

> - Calculated amount #475 

> So that the EDI can send the result in RSM-019 to the market actors.

 - [ ] Given a wholesale calculation, when started, Then the aggregated result is in hourly (PT1H) resolution.
 

# Tasks
#### Python:
 - [ ] ~Investigate if some values can be added to input tables during the migration from gold layer to wholesale:~ https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/gh/energinet-datahub/team-volt/176
      - [ ]  ~Refac python code?~ 
 - [x]  @energinet-ajw AWAITING VOLT
      - [x]  Can energy supplier id and balance responsible can be added? Yes. @energinet-ajw
      - [x]  Other values? No. @energinet-ajw
- [x] Add new calculation result type column ('amount_per_charge', 'monthly_amount_per_charge', 'total_monthly_amount') @JesperGomes 
- [x] Distinguish between charge (input) resolution and (output) resolution  @JesperGomes 
  
 #### .NET
 - [x] Publish AmountPerChargeResultProducedV1/MonthlyAmountPerChargeResultProducedV1 @JesperGomes 
 - [x] Write basic domain test that asserts number of service bus message @JesperGomes 
 - [x] Refactor `IntegrationEventProvider` to be more robust to changes in any _results_ or _events_ or _messages_ classes @dstenroejl 
 - [x] Update contracts nuget  with new events @dstenroejl 
 - [x] Use amount_type to determine event factory class @JesperGomes 
 - [x]  Add currency to wholesale result events  @JesperGomes 

### Done tasks:
 - [x] Contract tests of new (charge-related enums) 
      - [x] Contract test of ChargeUnit (QuantityUnit) @energinet-ajw
      - [x] Contract test of Charge resolution @energinet-ajw
      - [x] Contract test of Charge type @energinet-ajw
      - [x] Contract test of Charge quality  @energinet-ajw
 - [x] Disabling acceptance tests (domain tests) locally should not trigger calculation (see note 1) @dstenroejl
 - [x] **energy_supplier_id** must not be null in wholesale_results delta table 
      - [x] update energy_supplier_id in wholesale_results_schema @energinet-ajw
      - [x] add new sql script that sets energy_supplier_id to NOT NULL @energinet-ajw
      - [x] schema guard in wholesale calculation (in wholesale_calculation.execute())  @energinet-ajw
      - [x] document why **energy_supplier_id** must not be null on schema @energinet-ajw
 - [x] Find DocString format and document installation @energinet-ajw
 - [x] Streamline exception types in mappers and unit tests mappers @dstenroejl [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1522]

# Note
1: Currently when we disable acceptance tests (domain tests) locally they still trigger a calculation because it's triggered in the fixture initialization and not the Fact. This should be changed so we don't waste time. We can look into using the Lazy<T> to lazy trigger the calculation. Ask Dan if this is not explained well enough.
