### ISSUE TITLE
[Mandalorian] Versionsnummer på beregnings resultater bliver publiseret til EDI.

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#512]
# Synopsis
Som aktør 
vil jeg se versions nummer på beregningsresultaterne for balance fiksering og engrosafregning
så jeg ved hvilke resultater der er nyest.

# Accept kriterier
- Følgende accept kriterer gælder for følgende beregning typer: 

Balancefiksering	Unik Versions Tæller 
Engrosfiksering	Unik versions  Tæller
Korrektion 1	        Unik versions Tæller 
Korrektion 2	        Unik versions Tæller
Korrektion 3	        Unik version Tæller 

- [x] Givet en balance fiksering, når afsluttet succesfuldt så bliver der sat versionsnummer på beregningsresultaterne udtrykt ved et positivt heltal. (Version nummer feltet er "String") [#62](https://github.com/Energinet-DataHub/team-mandalorian/issues/62#issue-1965638555) 

- [x] Givet balance fiksering er afsluttet, når versionsnummer er sat på bergningsresultatter, så bliver versionsnummer sendt til EDI. [#138](https://github.com/Energinet-DataHub/team-mandalorian/issues/138#issue-2065436347)

- [ ] Givet en engrosfiksering eller korrektionsafreging, når afsluttet succesfuldt så bliver der sat versionsnummer på beregningsresultaterne udtrykt ved et positivt heltal. (Version nummer feltet er "String"). [#140](https://github.com/Energinet-DataHub/team-mandalorian/issues/140#issue-2065451693)

- [ ] Givet engrosfiksering eller korrektionsafreging er afsluttet, når versionsnummer er sat på bergningsresultatter, så bliver versionsnummer sendt til EDI. [#141](https://github.com/Energinet-DataHub/team-mandalorian/issues/141#issue-2065546052)

- [x] Givet en aktør anmoder om en beregning, når DataHub sender resultatet tilbage, så skal resultatet med den sidste versions nummer returneres [#133](https://github.com/Energinet-DataHub/team-mandalorian/issues/133#issue-2044986196)

- [ ] Beregninger med samme beregningstype må ikke køre på samme tid. [#143](https://github.com/Energinet-DataHub/team-mandalorian/issues/143#issue-2068778919).

# Noter

2 sprints

**Comment by BjarkeMeier** [comment]
Brainstorm:
- Jeg antager, at numrene ikke blot skal være unikke, men også stigende
- Må der være huller i numrene?
- Er det på denne feature, at vi skal sikre, at afregningsrapporter, anmodninger etc aldrig ser data fra delvist afsluttede beregninger?
