### ISSUE TITLE
Ensure logging works as expected in Databricks job

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/green-energy-hub#633]
## Synopsis
The settlement report Databricks job does log difference things to application insights. But is it logged under the correct cloud role name? Should we have logging integration tests as we have for CalculatorJob?

Also, we should move logging to a shared package

## Acceptance criteria
- [x] Log messages from settlement reports can be found in application insights
- [x] Spans are visible to see in application insights
- [x] Log messages contain the report id
- [x] Integration test of logging (like for the calculator job) has been implemented for the settlement report job
- [x] Integration test of logging has been implemented for the shared python package
- [x] Logging functionality is moved to a shared package and is used in both calculator job and settlement report job

## Tech Notes
Please see the description on #834. #834 was a duplicate and has been closed.

## Tasks
- [x] Add Application Insights connection string for logger
- [x] Add spans to definitions
- [x] Move record_exception to a shared location
- [x] Report id being passed to logger
- [x] Logging functionality is moved to a shared package and is used in both calculator job and settlement report job
- [x] Decorators don't log to Databricks UI. Therefore additional logs are added at the beginning of some methods. 
- [x] Make integration test in settlement reports 
- [x] Make integration test in shared package

**Comment by cenh-halfspace** [comment]
Screenshot of logging:
<img width="1274" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--418637d1b5bce0a03a8ea5b3f6c34f20e3e1de9f/image.png" alt="image.png" />

Screenshot of spans:
<img width="1338" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bf82989f839c5d02a5f5a99dd09fe01188d708b/image.png" alt="image.png" />
