### ISSUE TITLE
EN 31: Aktør stamdata

### ISSUE THREAD

**Issue by johoffma** [Energinet-DataHub/green-energy-hub#635]
# Produkt mål
Etablering af relationel model for aktør stamdata

#### Værdistrøm

# Success metrikker

# Risici & mitigerende handlinger

## Forretningskonsulent(er)
<Indsæt navn(e)>

## Arkitekt(er)
@Sondergaard @mrfoxdk @johoffma 

**Shoutout i POG:** Hvilke stakeholders skal involveres i dette produktmål, baseret på det vi har læst? 

# Tidsperspektiv
Inden 1. januar 2025

# Acceptkriterier
_Hvad står vi med i hånden nå vi er færdige? Hvad kan produktet når vi har nået produktmålet?_
_Nogle af acceptkriterierne kan evt. flyttes til underliggende feature_
**Aktør stamdata**
- [ ] Der er et godkendt E/R diagram, der omfavner alle aktør stamdata
- [ ] Der er truffet beslutning for, hvilken type SQL Server vi skal benytte
- [ ] Der er truffet beslutning for, hvordan ændringer til skema og data håndteres fremadrettet
- [ ] Der er truffet beslutning for, hvordan vi vil få indhold ind i aktør stamdata tabellerne i fase 2
https://miro.com/app/board/uXjVNi6e6Nw=/?moveToWidget=3458764581979547826&cot=14
- [ ] Der er lavet en prøve migrering af aktør stamdata
- [ ] Der er lavet en generel implementering i C# for hvordan vi læser aktør stamdata
- [ ] Der er lavet en generel implementering i C# for hvordan vi opdaterer aktør stamdata
- [ ] Validering af arkitektur og design er gennemført ved PoC
- [ ] Etablering af datamodel der sikrer transparens imellem proces og stamdata

**Comment by johoffma** [comment]
Udskilt fra EN 22, der tidligere indeholdet både procesmotor og aktør stamdata
