### ISSUE TITLE
Test af tidsserie csv generering 

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/green-energy-hub#638]
## Synopsis
Formål er at opnå confidence på det foreløbigt implementerede.

## Acceptance Criteria
- [x] Tests verificerer tidsserier csv at
  - [x] Store filer splitter (givet job parameter)
  - [x] Rækker i filer sorteres korrekt
  - [x] Data i CSV filer er korrekt

## Tasks
- [x] Unit test create_time_series(...) 
- [x] Unit test time_series_writer.write(...) for tidsserier @cenh-halfspace 
- [x] Test task flowet for time_series @JesperGomes 

Se evt. eksisterende løsning eller [denne](https://energinet.atlassian.net/wiki/spaces/D3/pages/655818851/Som+akt+r+vil+jeg+kunne+hente+mine+egne+afregningsrapporter+og+grundlag+fra+DataHub+3.0) dokumentation.
